# Generated by Django 4.0.4 on 2022-05-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_category_options_alter_item_accepted_offer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='published_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
