# Generated by Django 4.0.4 on 2022-05-03 11:31

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_alter_item_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='published_at',
            field=models.DateField(default=django.utils.datetime_safe.date.today),
        ),
        migrations.AlterField(
            model_name='item',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
