# Generated by Django 4.0.4 on 2022-05-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_alter_item_published_at_alter_item_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='items',
            field=models.ManyToManyField(to='item.item'),
        ),
        migrations.DeleteModel(
            name='CategoryItem',
        ),
    ]
