# Generated by Django 4.0.4 on 2022-05-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_remove_category_items_item_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.TextField(),
        ),
    ]
