# Generated by Django 4.0.4 on 2022-05-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_remove_item_image_url_item_image'),
        ('item', '0012_sale_card_cvv_sale_card_name_sale_card_number_and_more'),
    ]

    operations = [
    ]
