# Generated by Django 4.0.4 on 2022-05-11 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0016_alter_item_image_itemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='items'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='item.item'),
        ),
    ]
