# Generated by Django 4.0.4 on 2022-05-12 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0017_item_banner_alter_itemimage_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='highest_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highest_offer', to='item.offer'),
        ),
    ]
