# Generated by Django 4.0.4 on 2022-05-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('Offer_accepted', 'Offer Accepted'), ('Offer_rejected', 'Offer Rejected'), ('New_offer', 'New Offer'), ('Message', 'Message')], default='Message', max_length=14),
        ),
    ]
