# Generated by Django 4.0.4 on 2022-05-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_alter_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('Offer_accepted', 'Offer Accepted'), ('Offer_rejected', 'Offer Rejected'), ('Offer_new', 'New Offer'), ('Sale_completed', 'Sale Completed'), ('Message', 'Message')], default='Message', max_length=14),
        ),
    ]
