# Generated by Django 4.0.4 on 2022-05-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_alter_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('Offer_accepted', 'Offer Accepted'), ('Offer_rejected', 'Offer Rejected'), ('Offer_new', 'New Offer'), ('Sale_completed', 'Sale Completed'), ('Item_inquiry', 'Item inquiry'), ('Message', 'Message')], default='Message', max_length=14),
        ),
    ]
