# Generated by Django 4.0.4 on 2022-05-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_country_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avg_rating',
            field=models.IntegerField(default=5),
        ),
    ]
