# Generated by Django 4.0.4 on 2022-05-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_userprofile_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image_url',
            field=models.CharField(blank=True, default='/static/images/generic-profile.png', max_length=191, null=True),
        ),
    ]
