# Generated by Django 4.0.4 on 2022-05-06 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_userprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image_url',
        ),
    ]
